In [1]:
import pandas as pd

sales = pd.read_csv("../data/sales.csv")
customers = pd.read_csv("../data/customers.csv")
books = pd.read_csv("../data/books.csv")

In [2]:
merged = pd.merge(
    sales,
    books,
    on="Book_ID"
)

merged["Revenue"] = (
    merged["Quantity"] *
    merged["Price"]
)

In [3]:
customer_data = (
    merged.groupby(
        "Customer_ID"
    )["Revenue"]
    .sum()
    .reset_index()
)

customer_data.head()

  Customer_ID  Revenue
0        C001    43430
1        C002    85344
2        C003    48743
3        C004    82621
4        C005    57602

In [4]:
from sklearn.cluster import KMeans

In [5]:
X = customer_data[["Revenue"]]

kmeans = KMeans(
    n_clusters=3,
    random_state=42
)

customer_data["Cluster"] = (
    kmeans.fit_predict(X)
)

In [6]:
customer_data.head()

  Customer_ID  Revenue  Cluster
0        C001    43430        1
1        C002    85344        0
2        C003    48743        1
3        C004    82621        0
4        C005    57602        1

In [7]:
customer_data.to_csv(
    "../reports/customer_segments.csv",
    index=False
)

In [8]:
import pandas as pd
from sklearn.cluster import KMeans

sales = pd.read_csv("../data/sales.csv")
books = pd.read_csv("../data/books.csv")

merged = pd.merge(
    sales,
    books,
    on="Book_ID"
)

merged["Revenue"] = (
    merged["Quantity"] *
    merged["Price"]
)

customer_data = (
    merged.groupby("Customer_ID")
    ["Revenue"]
    .sum()
    .reset_index()
)

X = customer_data[["Revenue"]]

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

customer_data["Cluster"] = (
    kmeans.fit_predict(X)
)

customer_data.to_csv(
    "../reports/customer_segments.csv",
    index=False
)

print("customer_segments.csv created successfully")

customer_segments.csv created successfully